name = "captcha_gleam_bot"
version = "1.0.0"

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
mist = ">= 4.0.4 and < 5.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
wisp = ">= 1.7.0 and < 2.0.0"
dotenv_gleam = ">= 1.0.7 and < 2.0.0"
telega = { git = "git@github.com:bondiano/telega-gleam", ref = "master" }
carpenter = ">= 0.3.1 and < 1.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
